channels: [] # The channel id that you wish to send this to e.g. channels: ['12345', '64789'] (Quotation Marks Necessary)
token: # e.g. token: 12345 (No Quotation Marks Necessary)
posts: 3 # The default number of posts to make
hentai_haven: {
  enabled: True, # Set to True if you wish to use the /r/hentai_irl feature
  posts: 0, # Number of posts to post, if the value is below 1 then it will use the default post number
  channels: [], # The channels in the same format as above. Leave empty if you wish to use the same channels.
  embed_colour: FF0000 # The Hexadecimal (RRGGBB) or Decimal value for the embed colour of the post. (Red by default)
    # Red = FF0000 or 16711680
    # Green = 00FF00 or 65280
    # Blue = 0000FF  or 255 etc.
}
reddit: { # You can add as many subreddits as you want just make an entry using the template below.  
  # Example:
  # Uncomment (remove the hashtags at the start) the text below to make the bot post reddit.com/r/hentai_irl posts
  # hentai_irl: { # This is the name of the subreddit. e.g. www.reddit.com/r/{subreddit_name}
  #  posts: 0, # Number of posts to post, if the value is below 1 then it will use the default post number
  #  channels: [], # The channels in the same format as above. Leave empty if you wish to use the same channels.
  # }, <- Remember to add the comma at the end.
}
